name: Release Application

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]"]

permissions: 
    contents: write

jobs:
    build:
        runs-on: ${{ matrix.os }}
        name: Build RLGym Learn GUI
        strategy:
            matrix:
                include:
                - os: windows-latest
                  artifact-name: app-windows
                  api-name: RLGym_Learn_API.exe
                  extension: exe
                  output-name: "RLGym Learn GUI Setup "
                - os: ubuntu-latest
                  artifact-name: app-linux
                  api-name: RLGym_Learn_API
                  extension: AppImage
                  output-name: "RLGym Learn GUI-"

        steps:
        - name: Checkout code
          uses: actions/checkout@v6
        - uses: actions/setup-node@v6
          with:
            node-version: 24
            registry-url: https://registry.npmjs.org/
            package-manager-cache: false # never use caching in release builds

        - name: Download latest release assets
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh release download --repo MrCrystAll/RLGym-Learn-API --pattern "${{matrix.api-name}}" --output ${{matrix.api-name}}
        
        - name: Build
          run: |
            npm install
            npm run dist
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Generate output names
          shell: bash
          run: |
            NAME="${{matrix.output-name}}$(node -e "process.stdout.write(require('./package').version)").${{matrix.extension}}"
            echo "OUTPUT_NAME=$NAME" >> $GITHUB_ENV

        - name: Upload API binary as artifact
          uses: actions/upload-artifact@v7
          with:
            name: ${{ matrix.artifact-name }}
            path: ./dist/${{ env.OUTPUT_NAME }}
            retention-days: 1 # only needed during this workflow run

    release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Checkout code
          uses: actions/checkout@v6

        - name: Download Windows build
          uses: actions/download-artifact@v8
          with:
            name: app-windows
            path: ./release-files/

        - name: Download Linux build
          uses: actions/download-artifact@v8
          with:
            name: app-linux
            path: ./release-files/

        - name: Extract release notes from CHANGELOG.md
          id: extract_release_notes
          uses: ffurrer2/extract-release-notes@v3

        - name: Create Release
          uses: softprops/action-gh-release@v2
          with:
            name: Release ${{ github.ref_name }}
            tag_name: ${{ github.ref_name }}
            draft: false
            prerelease: false
            files: ./release-files/*
            body: ${{ steps.extract_release_notes.outputs.release_notes }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}